from datetime import datetime
from typing import List, Optional, Dict, Any
from sqlalchemy import (
    Column, String, Boolean, DateTime, Integer, 
    ForeignKey, JSON, Text, Index
)
from sqlalchemy.orm import relationship, declarative_base

Base = declarative_base()

class AdvisoryAssistant(Base):
    """
    Methodology champion that provides context-aware guidance.
    Mirrors GADOS Gold Standard.
    """
    __tablename__ = 'advisory_assistants'
    
    assistant_id = Column(String, primary_key=True)  # e.g., 'AGENT-ADVISOR-STARTUP-V1'
    tenant_id = Column(String, nullable=False, index=True)
    name = Column(String, nullable=False)
    description = Column(Text, nullable=False)
    methodology = Column(String, nullable=False)  # startup|scrum|kanban|safe|cmmi|itil
    
    activation_conditions = Column(JSON, nullable=False)
    authority = Column(String, nullable=False)  # advisory|recommending|enforcing|blocking
    advisory_scope = Column(JSON, nullable=False)  # List of AdvisoryScope
    target_roles = Column(JSON, nullable=False)  # List of RACI roles
    
    active = Column(Boolean, default=False, nullable=False)
    activated_at = Column(DateTime, nullable=True)
    
    message_count = Column(JSON, nullable=False, default=dict)
    
    created_at = Column(DateTime, nullable=False, default=datetime.utcnow)
    updated_at = Column(DateTime, nullable=False, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    messages = relationship('AdvisoryMessage', back_populates='assistant')

class AdvisoryMessage(Base):
    """
    Advisory message generated by an assistant.
    """
    __tablename__ = 'advisory_messages'
    
    id = Column(String, primary_key=True)
    assistant_id = Column(String, ForeignKey('advisory_assistants.assistant_id'), nullable=False, index=True)
    project_id = Column(String, nullable=True, index=True)
    tenant_id = Column(String, nullable=False, index=True)
    
    trigger_condition = Column(String, nullable=False)
    triggered_at = Column(DateTime, nullable=False, default=datetime.utcnow)
    
    target_role = Column(String, nullable=False)
    severity = Column(String, nullable=False)  # informational|recommendation|caution|blocking
    context = Column(String, nullable=False)
    
    message_template = Column(Text, nullable=False)
    explanation = Column(Text, nullable=False)
    suggested_action = Column(Text, nullable=False)
    
    actions = Column(JSON, nullable=False, default=list)
    status = Column(String, nullable=False, default='active')
    
    override_reason = Column(Text, nullable=True)
    
    created_at = Column(DateTime, nullable=False, default=datetime.utcnow)
    
    assistant = relationship('AdvisoryAssistant', back_populates='messages')
