#!/usr/bin/env node

/**
 * Generate UAT reports from test results
 * This script is called after UAT tests complete
 */

const fs = require('fs-extra');
const path = require('path');

async function generateReports() {
  console.log('Generating UAT reports...');

  const reportsDir = path.join(__dirname, '..', 'reports');
  const auditTrailPath = path.join(reportsDir, 'audit-trail.json');

  try {
    // Ensure reports directory exists
    await fs.ensureDir(reportsDir);

    // Check if audit trail exists
    if (!(await fs.pathExists(auditTrailPath))) {
      console.log('No audit trail found. Tests may not have run yet.');
      console.log('Run: npm run uat');
      process.exit(0);
    }

    // Read audit trail
    const auditTrail = await fs.readJson(auditTrailPath);
    console.log(`Found ${auditTrail.length} audit entries`);

    // Extract test results
    const testResults = auditTrail.filter(
      (entry) => entry.action === 'test_completed'
    );

    console.log(`Found ${testResults.length} test results`);

    // Generate summary
    const summary = {
      timestamp: new Date().toISOString(),
      totalTests: testResults.length,
      passed: testResults.filter((r) => r.status === 'passed').length,
      failed: testResults.filter((r) => r.status === 'failed').length,
      skipped: testResults.filter((r) => r.status === 'skipped').length,
    };

    summary.passRate =
      summary.totalTests > 0
        ? ((summary.passed / summary.totalTests) * 100).toFixed(2)
        : '0';

    // Write summary
    const summaryPath = path.join(reportsDir, 'summary.json');
    await fs.writeJson(summaryPath, summary, { spaces: 2 });
    console.log(`Summary written to: ${summaryPath}`);

    // Generate simple markdown report
    const mdReport = `# UAT Test Summary

**Generated:** ${new Date(summary.timestamp).toLocaleString()}

## Results

- **Total Tests:** ${summary.totalTests}
- **Passed:** ${summary.passed} (${summary.passRate}%)
- **Failed:** ${summary.failed}
- **Skipped:** ${summary.skipped}

## Status

${summary.failed === 0 ? '✅ All tests passed!' : '❌ Some tests failed'}

---

*Generated by MergePRCockPit UAT Testing Framework*
`;

    const mdPath = path.join(reportsDir, 'latest-summary.md');
    await fs.writeFile(mdPath, mdReport);
    console.log(`Markdown report written to: ${mdPath}`);

    console.log('\n✅ Report generation complete!');
    console.log(`   View reports in: ${reportsDir}`);
  } catch (error) {
    console.error('Error generating reports:', error);
    process.exit(1);
  }
}

generateReports();
